from datetime import date

from dateutil.relativedelta import relativedelta

from app.models.task import Category, Frequency, Priority, Season

today = date.today()

SEED_TASKS = [
    # === WEEKLY ===
    {
        "name": "Hot tub water test & chemical balance",
        "description": "Test pH, alkalinity, and sanitizer levels. Adjust as needed.",
        "category": Category.HOT_TUB,
        "frequency": Frequency.WEEKLY,
        "priority": Priority.P2,
        "estimated_minutes": 15,
    },

    # === MONTHLY ===
    {
        "name": "Hot tub filter rinse",
        "description": "Remove and rinse filter cartridge with garden hose.",
        "category": Category.HOT_TUB,
        "frequency": Frequency.MONTHLY,
        "priority": Priority.P2,
        "estimated_minutes": 10,
    },
    {
        "name": "Check/replace HVAC air filters",
        "description": "Inspect air filters; replace if dirty. Check all returns.",
        "category": Category.HVAC,
        "frequency": Frequency.MONTHLY,
        "priority": Priority.P1,
        "estimated_minutes": 15,
    },
    {
        "name": "Test smoke & CO detectors",
        "description": "Press test button on every smoke and CO detector in the house.",
        "category": Category.SAFETY,
        "frequency": Frequency.MONTHLY,
        "priority": Priority.P1,
        "estimated_minutes": 10,
    },
    {
        "name": "Inspect fire extinguishers",
        "description": "Confirm pressure gauge is in the green zone and pin/seal is intact.",
        "category": Category.SAFETY,
        "frequency": Frequency.MONTHLY,
        "priority": Priority.P1,
        "estimated_minutes": 5,
    },
    {
        "name": "Run water in unused fixtures",
        "description": "Run taps and flush toilets in guest baths to prevent P-trap dry-out and sewer gas.",
        "category": Category.PLUMBING,
        "frequency": Frequency.MONTHLY,
        "priority": Priority.P2,
        "estimated_minutes": 10,
    },
    {
        "name": "Test GFCI outlets",
        "description": "Press test/reset on all GFCI outlets (kitchen, bath, garage, exterior).",
        "category": Category.ELECTRICAL,
        "frequency": Frequency.MONTHLY,
        "priority": Priority.P1,
        "estimated_minutes": 10,
    },
    {
        "name": "Clean range hood filter",
        "description": "Soak range hood filter in degreasing solution. Grease buildup is a fire hazard.",
        "category": Category.APPLIANCES,
        "frequency": Frequency.MONTHLY,
        "priority": Priority.P2,
        "estimated_minutes": 20,
    },

    # === QUARTERLY ===
    {
        "name": "Hot tub deep clean & filter soak",
        "description": "Deep clean hot tub shell, soak filter cartridge in cleaning solution overnight.",
        "category": Category.HOT_TUB,
        "frequency": Frequency.QUARTERLY,
        "priority": Priority.P2,
        "estimated_minutes": 60,
    },
    {
        "name": "Test water heater pressure relief valve",
        "description": "Lift the T&P valve lever briefly — water should flow freely and stop when released.",
        "category": Category.PLUMBING,
        "frequency": Frequency.QUARTERLY,
        "priority": Priority.P1,
        "estimated_minutes": 10,
    },
    {
        "name": "Vacuum refrigerator coils",
        "description": "Vacuum coils underneath/behind the fridge to maintain efficiency.",
        "category": Category.APPLIANCES,
        "frequency": Frequency.QUARTERLY,
        "priority": Priority.P2,
        "estimated_minutes": 15,
    },
    {
        "name": "Clean dryer vent & lint ductwork",
        "description": "Clean lint from the entire vent run, not just the trap. Lint buildup is a fire hazard.",
        "category": Category.APPLIANCES,
        "frequency": Frequency.QUARTERLY,
        "priority": Priority.P1,
        "estimated_minutes": 30,
    },
    {
        "name": "Check washing machine hoses",
        "description": "Inspect supply hoses for bulges, cracks, or leaking. Replace every 3-5 years.",
        "category": Category.APPLIANCES,
        "frequency": Frequency.QUARTERLY,
        "priority": Priority.P2,
        "estimated_minutes": 5,
    },
    {
        "name": "Clean bathroom exhaust fans",
        "description": "Remove covers, vacuum dust and lint from fans and housing.",
        "category": Category.HVAC,
        "frequency": Frequency.QUARTERLY,
        "priority": Priority.P3,
        "estimated_minutes": 20,
    },
    {
        "name": "Treat drains with enzyme cleaner",
        "description": "Use enzyme-based drain cleaner in all drains to prevent buildup.",
        "category": Category.PLUMBING,
        "frequency": Frequency.QUARTERLY,
        "priority": Priority.P3,
        "estimated_minutes": 15,
    },

    # === SEASONAL — SPRING ===
    {
        "name": "Schedule professional A/C tune-up",
        "description": "Technician checks refrigerant, cleans coils, inspects electrical before cooling season.",
        "category": Category.HVAC,
        "frequency": Frequency.SEASONAL,
        "season": Season.SPRING,
        "priority": Priority.P1,
        "estimated_minutes": 15,
    },
    {
        "name": "Summerize snow equipment",
        "description": "Stabilize fuel or drain, clean, and store snow blower and related equipment.",
        "category": Category.OUTDOOR,
        "frequency": Frequency.SEASONAL,
        "season": Season.SPRING,
        "priority": Priority.P2,
        "estimated_minutes": 45,
    },
    {
        "name": "Start up fruit tree irrigation",
        "description": "Turn on underground line to the 2 fruit tree taps. Check for leaks and proper flow.",
        "category": Category.OUTDOOR,
        "frequency": Frequency.SEASONAL,
        "season": Season.SPRING,
        "priority": Priority.P2,
        "estimated_minutes": 20,
    },
    {
        "name": "Check exterior faucets for freeze damage",
        "description": "Turn on all outdoor faucets and hose bibs; check for leaks from winter freeze damage.",
        "category": Category.PLUMBING,
        "frequency": Frequency.SEASONAL,
        "season": Season.SPRING,
        "priority": Priority.P1,
        "estimated_minutes": 15,
    },
    {
        "name": "Clean gutters & downspouts (spring)",
        "description": "Remove debris, flush with hose, verify downspouts direct water away from foundation.",
        "category": Category.EXTERIOR,
        "frequency": Frequency.SEASONAL,
        "season": Season.SPRING,
        "priority": Priority.P1,
        "estimated_minutes": 90,
    },
    {
        "name": "Inspect roof",
        "description": "Check for missing, cracked, or curling shingles. Inspect flashing around vents and chimney.",
        "category": Category.EXTERIOR,
        "frequency": Frequency.SEASONAL,
        "season": Season.SPRING,
        "priority": Priority.P1,
        "estimated_minutes": 30,
    },
    {
        "name": "Power wash exterior surfaces",
        "description": "Power wash siding, deck, patio, driveway, and walkways.",
        "category": Category.EXTERIOR,
        "frequency": Frequency.SEASONAL,
        "season": Season.SPRING,
        "priority": Priority.P3,
        "estimated_minutes": 180,
    },
    {
        "name": "Inspect & repair exterior caulking",
        "description": "Check caulking around windows, doors, siding joints, and where utilities enter the house.",
        "category": Category.EXTERIOR,
        "frequency": Frequency.SEASONAL,
        "season": Season.SPRING,
        "priority": Priority.P2,
        "estimated_minutes": 60,
    },
    {
        "name": "Trim trees & shrubs away from house",
        "description": "Maintain 3+ feet clearance from siding and roof. Branches invite pests and cause damage.",
        "category": Category.OUTDOOR,
        "frequency": Frequency.SEASONAL,
        "season": Season.SPRING,
        "priority": Priority.P2,
        "estimated_minutes": 120,
    },
    {
        "name": "Service lawn mower",
        "description": "Change oil, sharpen blades, replace spark plug, replace air filter.",
        "category": Category.OUTDOOR,
        "frequency": Frequency.SEASONAL,
        "season": Season.SPRING,
        "priority": Priority.P2,
        "estimated_minutes": 60,
    },
    {
        "name": "Schedule pest / termite inspection",
        "description": "Annual professional inspection for termites and other pests.",
        "category": Category.PEST,
        "frequency": Frequency.SEASONAL,
        "season": Season.SPRING,
        "priority": Priority.P2,
        "estimated_minutes": 15,
    },

    # === SEASONAL — FALL ===
    {
        "name": "Schedule professional furnace tune-up",
        "description": "Technician inspects heat exchanger, burners, ignition, and safety controls before heating season.",
        "category": Category.HVAC,
        "frequency": Frequency.SEASONAL,
        "season": Season.FALL,
        "priority": Priority.P1,
        "estimated_minutes": 15,
    },
    {
        "name": "Winterize lawn equipment",
        "description": "Stabilize fuel or drain, clean, and store mower, trimmer, and related equipment.",
        "category": Category.OUTDOOR,
        "frequency": Frequency.SEASONAL,
        "season": Season.FALL,
        "priority": Priority.P2,
        "estimated_minutes": 45,
    },
    {
        "name": "Blow out & winterize outdoor hoses/faucets",
        "description": "Disconnect hoses, close interior shut-off valves, open hose bibs to drain.",
        "category": Category.PLUMBING,
        "frequency": Frequency.SEASONAL,
        "season": Season.FALL,
        "priority": Priority.P1,
        "estimated_minutes": 30,
    },
    {
        "name": "Winterize fruit tree irrigation",
        "description": "Blow out underground line to fruit tree taps. Shut off supply valve.",
        "category": Category.OUTDOOR,
        "frequency": Frequency.SEASONAL,
        "season": Season.FALL,
        "priority": Priority.P1,
        "estimated_minutes": 20,
    },
    {
        "name": "Clean gutters & downspouts (fall)",
        "description": "Clean gutters after leaves have fallen. Check downspout flow.",
        "category": Category.EXTERIOR,
        "frequency": Frequency.SEASONAL,
        "season": Season.FALL,
        "priority": Priority.P1,
        "estimated_minutes": 90,
    },
    {
        "name": "Inspect gas fireplace & chimney",
        "description": "Annual inspection of gas fireplace. Check pilot, thermocouple, glass, venting, and chimney cap.",
        "category": Category.HVAC,
        "frequency": Frequency.SEASONAL,
        "season": Season.FALL,
        "priority": Priority.P1,
        "estimated_minutes": 30,
    },
    {
        "name": "Caulk & seal exterior gaps",
        "description": "Seal gaps around windows, doors, and foundation to prevent cold air and pest entry.",
        "category": Category.EXTERIOR,
        "frequency": Frequency.SEASONAL,
        "season": Season.FALL,
        "priority": Priority.P2,
        "estimated_minutes": 60,
    },
    {
        "name": "Reverse ceiling fan direction",
        "description": "Switch to clockwise for winter — pushes warm air down from ceiling.",
        "category": Category.HVAC,
        "frequency": Frequency.SEASONAL,
        "season": Season.FALL,
        "priority": Priority.P3,
        "estimated_minutes": 10,
    },
    {
        "name": "Aerate & overseed lawn",
        "description": "Core aerate and overseed cool-season grass. Fall is ideal timing.",
        "category": Category.OUTDOOR,
        "frequency": Frequency.SEASONAL,
        "season": Season.FALL,
        "priority": Priority.P3,
        "estimated_minutes": 120,
    },

    # === ANNUAL ===
    {
        "name": "Full water heater drain & flush",
        "description": "Completely drain and refill water heater to remove sediment buildup.",
        "category": Category.PLUMBING,
        "frequency": Frequency.ANNUAL,
        "priority": Priority.P1,
        "estimated_minutes": 45,
    },
    {
        "name": "Inspect water heater anode rod",
        "description": "Check anode rod for corrosion. Replace every 3-5 years to prevent tank corrosion.",
        "category": Category.PLUMBING,
        "frequency": Frequency.ANNUAL,
        "priority": Priority.P2,
        "estimated_minutes": 30,
    },
    {
        "name": "Replace smoke detector batteries",
        "description": "Replace batteries in all smoke detectors, even hardwired units. Replace units every 10 years.",
        "category": Category.SAFETY,
        "frequency": Frequency.ANNUAL,
        "priority": Priority.P1,
        "estimated_minutes": 30,
    },
    {
        "name": "Replace CO detector batteries",
        "description": "Replace batteries in all CO detectors. Replace units every 5-7 years.",
        "category": Category.SAFETY,
        "frequency": Frequency.ANNUAL,
        "priority": Priority.P1,
        "estimated_minutes": 20,
    },
    {
        "name": "Exercise all shut-off valves",
        "description": "Open/close main water shut-off and individual fixture valves so they don't seize.",
        "category": Category.PLUMBING,
        "frequency": Frequency.ANNUAL,
        "priority": Priority.P2,
        "estimated_minutes": 30,
    },
    {
        "name": "Deep-clean major appliances",
        "description": "Dishwasher (clean filter, run cleaner), washing machine (clean gasket, run cleaner), fridge (drip pan, water filter).",
        "category": Category.APPLIANCES,
        "frequency": Frequency.ANNUAL,
        "priority": Priority.P3,
        "estimated_minutes": 90,
    },
    {
        "name": "Inspect foundation for cracks",
        "description": "Walk perimeter and inspect foundation. Hairline cracks are normal; horizontal or >1/4in cracks need a pro.",
        "category": Category.EXTERIOR,
        "frequency": Frequency.ANNUAL,
        "priority": Priority.P1,
        "estimated_minutes": 20,
    },
    {
        "name": "Inspect garage door hardware",
        "description": "Check springs, cables, and rollers. Lubricate tracks and hinges. Test auto-reverse and balance.",
        "category": Category.GARAGE,
        "frequency": Frequency.ANNUAL,
        "priority": Priority.P2,
        "estimated_minutes": 30,
    },
    {
        "name": "Visual inspect electrical panel",
        "description": "Look for scorch marks, corrosion, or overheating signs. Schedule electrician if anything abnormal.",
        "category": Category.ELECTRICAL,
        "frequency": Frequency.ANNUAL,
        "priority": Priority.P1,
        "estimated_minutes": 10,
    },
    {
        "name": "Inspect attic insulation & ventilation",
        "description": "Check insulation coverage and R-value. Ensure soffit and ridge vents are unblocked.",
        "category": Category.EXTERIOR,
        "frequency": Frequency.ANNUAL,
        "priority": Priority.P2,
        "estimated_minutes": 30,
    },
]
