"""add notification_channels table

Revision ID: 7fe3b69d2024
Revises: 609643f94469
Create Date: 2026-03-26 12:25:21.448286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe3b69d2024'
down_revision: Union[str, None] = '609643f94469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel_type', sa.Enum('EMAIL', 'WEBHOOK', 'NTFY', name='channeltype'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('notify_overdue', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notify_due_today', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notify_upcoming_days', sa.Integer(), server_default='7', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_channels')
    # ### end Alembic commands ###
