"""add priority duration weekend cost supplies photos

Revision ID: 8c184d5b9192
Revises: 2d5bff8f90f1
Create Date: 2026-03-25 16:57:41.669207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c184d5b9192'
down_revision: Union[str, None] = '2d5bff8f90f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('quantity_on_hand', sa.Integer(), server_default='0', nullable=False),
    sa.Column('quantity_per_use', sa.Integer(), server_default='1', nullable=False),
    sa.Column('annual_uses', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task_completions', sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('task_completions', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.add_column('task_completions', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    priority_enum = sa.Enum('P1', 'P2', 'P3', name='priority')
    priority_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('tasks', sa.Column('priority', priority_enum, server_default='P2', nullable=False))
    op.add_column('tasks', sa.Column('estimated_minutes', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('prefer_weekend', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'prefer_weekend')
    op.drop_column('tasks', 'estimated_minutes')
    op.drop_column('tasks', 'priority')
    sa.Enum(name='priority').drop(op.get_bind(), checkfirst=True)
    op.drop_column('task_completions', 'duration_minutes')
    op.drop_column('task_completions', 'photo_url')
    op.drop_column('task_completions', 'cost')
    op.drop_table('supplies')
    # ### end Alembic commands ###
