"""add assets table and task asset_id fk

Revision ID: 9069eaeed352
Revises: 8c184d5b9192
Create Date: 2026-03-25 18:14:24.919871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9069eaeed352'
down_revision: Union[str, None] = '8c184d5b9192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', postgresql.ENUM('HVAC', 'PLUMBING', 'ELECTRICAL', 'EXTERIOR', 'OUTDOOR', 'APPLIANCES', 'SAFETY', 'HOT_TUB', 'GARAGE', 'PEST', 'OTHER', name='category', create_type=False), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model_number', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('warranty_expires', sa.Date(), nullable=True),
    sa.Column('expected_lifespan_years', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('manual_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'assets', ['asset_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'asset_id')
    op.drop_table('assets')
    # ### end Alembic commands ###
